name: Build Test

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle

      - name: Cache
        uses: actions/cache@v3.3.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew build

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: 'build/test-results/test/TEST-*.xml'

      - name: JUnit Report Action
        uses: mikepenz/action-junit-report@v4.0.1
        if: always()
        with:
          report_paths: 'build/test-results/test/TEST-*.xml'
