name: MMA prod Ci/Cd

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: MMAApplication
          path: build/libs/mma-*-SNAPSHOT.jar

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: MMAApplication
          path: /home/pi/mma/

      - name: Run Build Script
        run: source /home/pi/mma/run.sh
